name: Atualizar README

on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v4

      - name: Adicionar conteúdo no README.md
        run: echo "# Titulo adicionado pelo GitHub Actions" >> readme.md
          
      - name: Configurar usuário Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fazer commit e push
        run: |
          git checkout -b actions/update-readme
          git add README.md
          git commit -m "Atualiza README.md via Actions"
          git push origin actions/update-readme
